import { VehicleOption, CouponOffer } from '../types';

export const vehicleCategories: VehicleOption[] = [
  {
    id: 'veh-hatch',
    name: 'WagonR / Indica',
    category: 'Hatchback',
    passengers: 4,
    luggage: 1,
    basePrice: 350,
    perKmRate: 11,
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=300&auto=format&fit=crop&q=80',
    tagline: 'Pocket-friendly rides for daily commute',
    eta: '3 mins away',
  },
  {
    id: 'veh-sedan',
    name: 'Dzire / Etios',
    category: 'Sedan',
    passengers: 4,
    luggage: 2,
    basePrice: 450,
    perKmRate: 13,
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=300&auto=format&fit=crop&q=80',
    tagline: 'Comfortable sedans with AC & extra legroom',
    eta: '4 mins away',
  },
  {
    id: 'veh-suv',
    name: 'Innova / Ertiga',
    category: 'SUV',
    passengers: 6,
    luggage: 3,
    basePrice: 750,
    perKmRate: 18,
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=300&auto=format&fit=crop&q=80',
    tagline: 'Spacious 6-seater for family & outstation',
    eta: '6 mins away',
  },
  {
    id: 'veh-prem-suv',
    name: 'Innova Crysta',
    category: 'Premium SUV',
    passengers: 7,
    luggage: 4,
    basePrice: 950,
    perKmRate: 22,
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=300&auto=format&fit=crop&q=80',
    tagline: 'Luxury travel with top-rated captains',
    eta: '8 mins away',
  },
  {
    id: 'veh-tt',
    name: 'Tempo Traveller (12 Seater)',
    category: 'Tempo Traveller',
    passengers: 12,
    luggage: 8,
    basePrice: 1800,
    perKmRate: 28,
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=300&auto=format&fit=crop&q=80',
    tagline: 'Group travel & temple tours across TN',
    eta: '15 mins away',
  },
];

export const activeOffers: CouponOffer[] = [
  { code: 'NESAMFIRST', discount: 'Flat ₹150 OFF', desc: 'Valid on first outstation or airport ride', validTill: '31 Aug 2026', minFare: 500, category: 'All', highlight: true },
  { code: 'AIRPORT50', discount: '₹50 OFF', desc: 'Flat discount on all airport drop & pickup rides', validTill: '15 Sep 2026', minFare: 350, category: 'Airport' },
  { code: 'OUTSTATION10', discount: '10% OFF', desc: 'Get up to ₹300 OFF on one-way & round outstation trips', validTill: '30 Sep 2026', minFare: 1500, category: 'Outstation' },
  { code: 'WEEKEND200', discount: '₹200 OFF', desc: 'Valid on Saturday & Sunday travel bookings', validTill: '31 Aug 2026', minFare: 2000, category: 'Outstation' },
];
